name: Create Archive

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'DoNotPullAWirtual.op'
        exclusions: 'LICENSE *.md *.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "DoNotPullAWirtual.op"
        token: ${{ secrets.GITHUB_TOKEN }}
